---
title: "Exploratory analysis"
output: ioslides_presentation
date: "Day 4, Data Science Basics in R Workshop"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
countries <- read.delim("https://raw.githubusercontent.com/seaneff/data-science-basics-2023/main/day2/exercise/countries.tsv")
```

## Measures of centrality

```{r echo = TRUE}
mean(countries$mds_per_10000capita)
```

```{r echo = TRUE}
median(countries$mds_per_10000capita)
```

## Measures of spread

```{r echo = TRUE}
var(countries$mds_per_10000capita)
```

```{r echo = TRUE}
sd(countries$mds_per_10000capita)
```

```{r echo = TRUE}
quantile(countries$mds_per_10000capita)
```

## Counts and rates

```{r echo = TRUE}
table(countries$who_region)
```
```{r echo = TRUE}
round(prop.table(table(countries$who_region)), 2)
```

## Basic summarization

```{r echo = TRUE}
summary(countries$mds_per_10000capita)
```

## Histogram

```{r echo = TRUE}
hist(countries$mds_per_10000capita)
```

## Histogram with labels

```{r echo = TRUE}
hist(countries$mds_per_10000capita,
     xlab = "MDs per 10,000 capita", ylab = "Frequency",
     main = "MDs per 10,000 capita,\nby country", col = "light blue")
```

## Scatterplot


```{r echo = TRUE}
plot(countries$mds_per_10000capita, 
     countries$nurses_midwives_per_10000capita,
     xlab = "MDs per 10,000 capita", ylab = "Nurses/midwives per 10,000 capita",
     main = "Nurses/midwives vs. MDs per capita")
```

## Exporting plots from R
```{r echo = TRUE}
hist(countries$mds_per_10000capita,
     xlab = "MDs per 10,000 capita", ylab = "Frequency",
     main = "MDs per 10,000 capita,\nby country", col = "light blue")
```

